name: Deploy Game Analytics pipeline

on:
  push:
    branches:
      -main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      users: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_REGION}}
    
    - name: Deploy to AWS
      run: npm run deploy